### ISSUE TITLE
Possible Bug - Using NPM install getting import unexpected token with Typescript

### ISSUE THREAD

**Issue by kentonbmax** [samuelneff/sequelize-auto-ts#13]
Error:
import generator = require("./sequelize-auto-ts");
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

[typescript-function-parameter-type-unexpected-token](http://stackoverflow.com/questions/20332577/typescript-function-parameter-type-unexpected-token)

**Comment by kentonbmax** [comment]
Change to cli.js and working now. Update readme.

**Comment by AJamesPhillips** [comment]
> Update readme.

@kentonbmax please submit a PR.

**Comment by samuelneff** [comment]
What did you change in cli.js? I install this project via npm to several other projects and have not run into this issue, although I'm not using the latest version of TypeScript.

**Comment by AJamesPhillips** [comment]
@samuelneff I think he means the README.md lists using the `cli.ts` instead of the `cli.js` file

**Comment by codemau5** [comment]
I am also experiencing this issue, also fixed by changing to cli.js
